import { z } from 'zod';
import { objectIdSchema } from '../../shared/validators';

export const timelineEventSchema = z.object({
  eventId: z.string().trim().min(1, 'Event ID is required'),
  eventType: z.enum(['CREATED', 'CONTACTED', 'COUNSELING_SCHEDULED', 'COUNSELING_COMPLETED', 'FOLLOW_UP', 'APPLIED', 'ENROLLED', 'ARCHIVED', 'NOTE_ADDED', 'STATUS_CHANGED']),
  description: z.string().trim().min(1, 'Description is required').max(1000),
  performedBy: objectIdSchema,
  performedByRole: z.enum(['SYSTEM', 'AI', 'COUNSELOR', 'ADMIN', 'STUDENT']),
});

export const leadScoreHistorySchema = z.object({
  score: z.coerce.number().int().min(0).max(100),
  reason: z.string().trim().min(1, 'Reason is required').max(500),
  generatedAt: z.coerce.date(),
  generatedBy: z.string().trim().min(1, 'Generated by is required'),
});

export const conversionSchema = z.object({
  isConverted: z.boolean().default(false),
  applicantId: z.string().trim().optional().or(z.literal('')),
  convertedAt: z.coerce.date().optional(),
});

export const createInquirySchema = z.object({
  inquiryId: z.string().trim().regex(/^INQ\d{6,10}$/, 'Inquiry ID must follow format INQ followed by 6-10 digits'),
  inquiryNumber: z.string().trim().regex(/^INQ-\d{4}-\d{6}$/, 'Inquiry number must follow format INQ-YYYY-NNNNNN'),
  fullName: z.string().trim().min(2, 'Full name must be at least 2 characters').max(100),
  firstName: z.string().trim().min(1, 'First name is required').max(50),
  lastName: z.string().trim().min(1, 'Last name is required').max(50),
  email: z.string().trim().email('A valid email is required').max(100),
  phone: z.string().trim().regex(/^\+?[0-9]{10,15}$/, 'A valid phone number is required'),
  dateOfBirth: z.coerce.date().optional(),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY']).optional(),
  preferredCommunication: z.enum(['EMAIL', 'PHONE', 'SMS', 'WHATSAPP']).optional(),
  country: z.string().trim().max(100).optional().or(z.literal('')),
  state: z.string().trim().max(100).optional().or(z.literal('')),
  city: z.string().trim().max(100).optional().or(z.literal('')),
  address: z.string().trim().max(500).optional().or(z.literal('')),
  qualification: z.enum(['HIGH_SCHOOL', 'INTERMEDIATE', 'DIPLOMA', 'BACHELORS', 'MASTERS', 'PHD', 'OTHER']).optional(),
  boardOrUniversity: z.string().trim().max(200).optional().or(z.literal('')),
  passingYear: z.coerce.number().int().min(1990).max(new Date().getFullYear() + 1).optional(),
  percentage: z.coerce.number().int().min(0).max(100).optional(),
  cgpa: z.coerce.number().int().min(0).max(10).optional(),
  category: z.string().trim().max(50).optional().or(z.literal('')),
  specialization: z.string().trim().max(100).optional().or(z.literal('')),
  preferredCourseId: objectIdSchema.optional(),
  aiRecommendedCourseIds: z.array(objectIdSchema).default([]),
  alternativeCourseIds: z.array(objectIdSchema).default([]),
  preferredDepartmentId: objectIdSchema.optional(),
  preferredCampus: z.string().trim().max(100).optional().or(z.literal('')),
  preferredAdmissionYear: z.string().trim().regex(/^\d{4}-\d{4}$/, 'Admission year must be in format YYYY-YYYY').optional().or(z.literal('')),
  budgetRange: z.string().trim().max(50).optional().or(z.literal('')),
  hostelRequired: z.boolean().default(false),
  transportRequired: z.boolean().default(false),
  source: z.enum(['WEBSITE', 'SOCIAL_MEDIA', 'REFERRAL', 'WALK_IN', 'CALL', 'EMAIL', 'WHATSAPP', 'EDUCATION_FAIR', 'OTHER']),
  campaign: z.string().trim().max(100).optional().or(z.literal('')),
  medium: z.string().trim().max(100).optional().or(z.literal('')),
  referralSource: z.string().trim().max(200).optional().or(z.literal('')),
  utmSource: z.string().trim().max(100).optional().or(z.literal('')),
  utmMedium: z.string().trim().max(100).optional().or(z.literal('')),
  utmCampaign: z.string().trim().max(100).optional().or(z.literal('')),
  campaignId: z.string().trim().max(50).optional().or(z.literal('')),
  inquiryDate: z.coerce.date(),
  status: z.enum(['NEW', 'CONTACTED', 'INTERESTED', 'APPLIED', 'ENROLLED', 'REJECTED', 'ARCHIVED']).default('NEW'),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']).default('MEDIUM'),
  aiSummary: z.string().trim().max(2000).optional().or(z.literal('')),
  aiLeadScore: z.coerce.number().int().min(0).max(100).optional(),
  aiLeadScoreHistory: z.array(leadScoreHistorySchema).default([]),
  aiConfidenceScore: z.coerce.number().int().min(0).max(100).optional(),
  aiRecommendedDepartmentId: objectIdSchema.optional(),
  aiIntent: z.enum(['HIGH_INTENT', 'MEDIUM_INTENT', 'LOW_INTENT', 'UNCERTAIN']).optional(),
  aiSentiment: z.enum(['POSITIVE', 'NEUTRAL', 'NEGATIVE']).optional(),
  aiRiskLevel: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(),
  aiNextBestAction: z.string().trim().max(500).optional().or(z.literal('')),
  aiConversationSummary: z.string().trim().max(3000).optional().or(z.literal('')),
  assignedCounselorId: objectIdSchema.optional(),
  assignedAt: z.coerce.date().optional(),
  counselorNotes: z.string().trim().max(2000).optional().or(z.literal('')),
  counselingMode: z.enum(['ONLINE', 'IN_PERSON', 'PHONE', 'VIDEO_CALL']).optional(),
  counselingOutcome: z.enum(['INTERESTED', 'NOT_INTERESTED', 'PENDING', 'APPLIED', 'ENROLLED']).optional(),
  nextFollowUpDate: z.coerce.date().optional(),
  lastContactDate: z.coerce.date().optional(),
  followUpCount: z.coerce.number().int().min(0).default(0),
  lastFollowUpResult: z.string().trim().max(500).optional().or(z.literal('')),
  timeline: z.array(timelineEventSchema).default([]),
  tags: z.array(z.string().trim()).default([]),
  conversion: conversionSchema.default({ isConverted: false }),
  isActive: z.boolean().default(true),
});

export const updateInquirySchema = createInquirySchema.partial().omit({
  inquiryId: true,
  inquiryNumber: true,
  email: true,
  phone: true,
  timeline: true,
});

export const inquiryQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  sort: z.string().trim().optional(),
  order: z.enum(['asc', 'desc']).default('desc'),
  search: z.string().trim().optional(),
  status: z.enum(['NEW', 'CONTACTED', 'INTERESTED', 'APPLIED', 'ENROLLED', 'REJECTED', 'ARCHIVED']).optional(),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']).optional(),
  source: z.enum(['WEBSITE', 'SOCIAL_MEDIA', 'REFERRAL', 'WALK_IN', 'CALL', 'EMAIL', 'WHATSAPP', 'EDUCATION_FAIR', 'OTHER']).optional(),
  preferredCourseId: z.string().trim().optional(),
  preferredDepartmentId: z.string().trim().optional(),
  assignedCounselorId: z.string().trim().optional(),
  aiIntent: z.enum(['HIGH_INTENT', 'MEDIUM_INTENT', 'LOW_INTENT', 'UNCERTAIN']).optional(),
  aiRiskLevel: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(),
  aiLeadScoreMin: z.coerce.number().int().min(0).max(100).optional(),
  aiLeadScoreMax: z.coerce.number().int().min(0).max(100).optional(),
  isActive: z.coerce.boolean().optional(),
  inquiryDateFrom: z.string().trim().optional(),
  inquiryDateTo: z.string().trim().optional(),
  nextFollowUpDateFrom: z.string().trim().optional(),
  nextFollowUpDateTo: z.string().trim().optional(),
  tag: z.string().trim().optional(),
});

export const assignCounselorSchema = z.object({
  counselorId: objectIdSchema,
});

export const updateStatusSchema = z.object({
  status: z.enum(['NEW', 'CONTACTED', 'INTERESTED', 'APPLIED', 'ENROLLED', 'REJECTED', 'ARCHIVED']),
  note: z.string().trim().max(500).optional().or(z.literal('')),
});

export const followUpSchema = z.object({
  result: z.string().trim().min(1, 'Follow up result is required').max(500),
  nextFollowUpDate: z.coerce.date().optional(),
  note: z.string().trim().max(1000).optional().or(z.literal('')),
});

export const bulkImportSchema = z.object({
  inquiries: z.array(createInquirySchema).min(1).max(500),
});

export const bulkUpdateSchema = z.object({
  ids: z.array(objectIdSchema).min(1).max(500),
  updates: updateInquirySchema,
});

export type TimelineEventInput = z.infer<typeof timelineEventSchema>;
export type LeadScoreHistoryInput = z.infer<typeof leadScoreHistorySchema>;
export type ConversionInput = z.infer<typeof conversionSchema>;
export type CreateInquiryInput = z.infer<typeof createInquirySchema>;
export type UpdateInquiryInput = z.infer<typeof updateInquirySchema>;
export type InquiryQueryInput = z.infer<typeof inquiryQuerySchema>;
export type AssignCounselorInput = z.infer<typeof assignCounselorSchema>;
export type UpdateStatusInput = z.infer<typeof updateStatusSchema>;
export type FollowUpInput = z.infer<typeof followUpSchema>;
export type BulkImportInput = z.infer<typeof bulkImportSchema>;
export type BulkUpdateInput = z.infer<typeof bulkUpdateSchema>;
